import { Header } from "@/components/Header";
import "./../styles/globals.css";
import { PromtInput } from "@/components/PromptInput";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* header */}
        <Header />

        {/* input part */}
        <PromtInput />

        {children}
      </body>
    </html>
  );
}
